pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/MJ1608/Kafka-OpenSearch-Integration.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                // Build the project (if needed)
                sh 'pip install -r requirements.txt'

                // Start Docker services
                sh 'docker-compose up -d'

                // Wait for services to initialize (adjust time based on your project's startup time)
                script {
                    sleep 300  // Wait for 5 minutes (adjust as necessary)
                }
            }
        }


        stage('Run Producer') {
            steps {
                // Run the Python producer script in background and capture PID
                script {
                    def producerProcess = sh(script: 'python3 producer/producer.py & echo $!', returnStdout: true).trim()
                    env.PRODUCER_PID = producerProcess
                }

                // Check if Kafka topic is created
                script {
                    def topicCreated = sh(script: "docker exec -i firstbuild-kafka1-1 kafka-topics.sh --list --bootstrap-server localhost:9092 | grep -Fx 'wiki'", returnStatus: true)
                    if (topicCreated == 0) {
                        echo 'Kafka topic "wiki" is created.'
                    } else {
                        error 'Failed to create Kafka topic "wiki".'
                    }
                }

                // Wait a bit for data to start being produced (adjust based on expected startup time)
                script {
                    sleep 10  // Wait for 10 seconds (adjust as necessary)
                }

                // Stop the producer script
                script {
                    sh "kill -TERM ${env.PRODUCER_PID}"
                }
            }
        }

        stage('Run Consumer') {
            steps {
                // Run the Python consumer script in background and capture PID
                script {
                    def consumerProcess = sh(script: 'python3 consumer/consumer.py & echo $!', returnStdout: true).trim()
                    env.CONSUMER_PID = consumerProcess
                }

                // Wait for consumer to finish (adjust based on expected runtime)
                script {
                    sleep 40  // Wait for 60 seconds (adjust as necessary)
                }

                // Verify OpenSearch index existence and state
                script {
                    try {
                        def response = sh(script: "curl -s -o /dev/null -w '%{http_code}' http://localhost:9200/wikimedia", returnStdout: true)
                        if (response.trim() == "200") {
                            echo 'OpenSearch index "wikimedia" is created and accessible.'
                        } else {
                            error 'Failed to verify OpenSearch index "wikimedia".'
                        }
                    } catch (Exception e) {
                        error "Failed to execute HTTP request: ${e.message}"
                    }
                }

                // Stop the consumer script
                script {
                    sh "kill -TERM ${env.CONSUMER_PID}"
                }
            }
        }
    }

    post {
        always {
            // Clean up resources (e.g., stop Docker containers)
            sh 'docker-compose down'
        }
    }
}
